### ISSUE TITLE
Support CSV from Fusion Tables

### ISSUE THREAD

**Issue by tokumine** [Vizzuality/cartodb-importer#6]
If somone uploads a CSV with a column where there might be KML lets try to detect it and import the geometry.

It could work as follow:

1) After import, read the first record.
2) If any of the columns start with , etc... then we know there is KML there
3) Create the_geom of the column with the corresponding data type (POINT, POLYGON, etc)
4) Use ST_GeomFromKML to update the_geom with that

**Comment by andrewxhill** [comment]
Right now, some of the post-import steps are happening after the cartodb-importer is finished (e.g. webmercator transform, cartodb_id, etc). I think some of these issues, varchar getting limited, string->int detection, kml->geom might be better to put at the time of all those other table table transformations, not the importer. What do you think?
