### ISSUE TITLE
numeric CSV data is imported as string

### ISSUE THREAD

**Issue by tokumine** [Vizzuality/cartodb-importer#7]
It seems that all CSV is imported as a string datatype. 

We would ideally test columns for numericness and use floating point if possible. 

This affects the georeferening dropdown as it can only see numeric types, and is a little weird for sql queries.

Test file: http://dl.dropbox.com/u/193220/late_flights.csv

**Comment by andrewxhill** [comment]
Yup, if we are going to clean up the Varchar(maxlen) issue, https://github.com/Vizzuality/cartodb/issues/179, this could be run in the same set of cleanup functions.
